on:
  push:
    branches:
      - develop
      - 'epic/**'
      - 'release/**'
name: Cache node modules

env:
  NODE_VERSION: '16'

jobs:
  cacheNodeModules:   
    name: Cache node_modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Installing root dependencies
        run: yarn --frozen-lockfile
      - name: Installing cypress dependencies
        working-directory: projects/storefrontapp-e2e-cypress
        run: yarn --frozen-lockfile
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: | 
            node_modules
            projects/storefrontapp-e2e-cypress/node_modules
            ~/.cache/Cypress
          key: nodemodules-${{ github.sha }}