on:
  workflow_dispatch:
    inputs:
      unreleased_sample_branch:
        description: Unreleased sample data branch or tag
        default: release/2105/next
        required: true
      current_sample_branch:
        description: current release sample data branch or tag
        default: 2105-4.3.7
        required: true
      previous_sample_branch:
        description: previous release sample data branch or tag
        default: 2105-3.4.8
        required: true

name: Publish Spartacus Sample Data to Spartacus CCv2 repository
jobs:
  publish_sample_data: 
    name: Publishing Spartacus Sample Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: create release with sample data assets
        env:
          SAMPLE_DATA_UNRELEASED: ${{ github.event.inputs.unreleased_sample_branch }}
          SAMPLE_DATA_CURRENT: ${{ github.event.inputs.current_sample_branch }}
          SAMPLE_DATA_PREVIOUS: ${{ github.event.inputs.previous_sample_branch }}
          GHT_USER: ${{ secrets.GHT_USER }}
          GHT_PRIVATE_REPO_TOKEN: ${{ secrets.GHT_PRIVATE_REPO_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TEMPORARY_TOKEN }}
        run: |
          ci-scripts/publish-sample-data.sh
